name: 'Terraform Apply'

on:
  push:
    branches:
      - master

permissions:
  contents: read
  pull-requests: write

jobs:
  changes:
    runs-on: ubuntu-latest
    outputs:
      directories: ${{ steps.detect_changes.outputs.directories }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Identify changed files in infra directory
        id: detect_changes
        run: |
          # Fetch full history of base branch
          git fetch --unshallow || true
          git fetch origin ${{ github.event.pull_request.base.ref }} --depth=1000 || true
      
          # Ensure base branch exists locally
          git checkout ${{ github.event.pull_request.base.ref }} || git checkout -b ${{ github.event.pull_request.base.ref }} origin/${{ github.event.pull_request.base.ref }}
      
          # Get changed files
          CHANGED_FILES=$(git diff --name-only origin/${{ github.event.pull_request.base.ref }}...${{ github.sha }} -- 'infra/**' || true)
      
          if [[ -z "$CHANGED_FILES" ]]; then
            echo "No changes detected in infra directory."
            echo "directories=[]" >> $GITHUB_OUTPUT
            exit 0
          fi
      
          echo "Changed files: $CHANGED_FILES"
      
          # Extract unique directories
          UNIQUE_DIRS=$(echo "$CHANGED_FILES" | xargs -n1 dirname | sort -u | jq -R -s -c 'split("\n")[:-1]')
          
          echo "directories=$UNIQUE_DIRS" >> $GITHUB_OUTPUT

  terraform:
    needs: changes
    name: "Terraform"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        directory: ${{ fromJSON(needs.changes.outputs.directories) }}
    defaults:
      run:
        working-directory: ${{ matrix.directory }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
 
      - name: Terraform Init
        id: init
        run: |
          git config --global url."https://oauth2:${{ secrets.MYTC }}@github.com".insteadOf https://github.com
          terraform init
        env:
          GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}
        continue-on-error: true
        
      - name: Terraform Apply
        id: apply
        run: terraform apply -auto-approve -input=false
        env:
          GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}
        continue-on-error: false
